CREATE TABLE products(
  product_id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(2000) NOT NULL, 
  price FLOAT NOT NULL,
  image_one TEXT NOT NULL,
  image_two TEXT NOT NULL,
  download_link VARCHAR(255) NOT NULL
);

INSERT INTO products (name, description, price, image_one, image_two, download_link)
VALUES ('Metal Texture Pack',
'Complete package with different metal surfaces for Cinema4D. Includes 235 4K meterials.',
49.00,
'https://i.imgur.com/EcOnEZW.png',
'fakeURL',
'fakeDownload'),
('Plaster Texture Pack',
'Complete package with different plaster surfaces for Cinema4D. Includes 202 4K meterials.',
39.00,
'https://i.imgur.com/d6thk10.png',
'fakeURL',
'fakeDownload'),
('Brick Texture Pack',
'Complete package with different brick surfaces for Cinema4D. Includes 190 4K meterials.',
39.00,
'https://i.imgur.com/kYixLeo.png',
'fakeURL',
'fakeDownload'),
('Gold Texture Pack',
'Complete package with different fabric surfaces for Cinema4D. Includes 148 4K meterials.',
25.00,
'https://i.imgur.com/UjPsicR.png',
'fakeURL',
'fakeDownload'),
('Fabric Texture Pack',
'Complete package with different fabric surfaces for Cinema4D. Includes 255 4K meterials.',
49.00,
'https://i.imgur.com/TZWg0sf.png',
'fakeURL',
'fakeDownload'),
('Marble Texture Pack',
'Complete package with different marble surfaces for Cinema4D. Includes 188 4K meterials.',
39.00,
'https://i.imgur.com/73tz8Pi.png',
'fakeURL',
'fakeDownload'),
('Wood Texture Pack',
'Complete package with different wood surfaces for Cinema4D. Includes 243 4K meterials.',
49.00,
'https://i.imgur.com/aMn6BcJ.png',
'fakeURL',
'fakeDownload'),
('Cardboard Texture Pack',
'Complete package with different cardboard surfaces for Cinema4D. Includes 135 4K meterials.',
25.00,
'https://i.imgur.com/RuAs3UC.png',
'fakeURL',
'fakeDownload'),
('Concrete Texture Pack',
'Complete package with different concrete surfaces for Cinema4D. Includes 225 4K meterials.',
49.00,
'https://i.imgur.com/A73yAFD.png',
'fakeURL',
'fakeDownload'),
('Potery Texture Pack',
'Complete package with different potery surfaces for Cinema4D. Includes 171 4K meterials.',
39.00,
'https://i.imgur.com/BEvBomH.png',
'fakeURL',
'fakeDownload');